modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/CERBON-MODS/Talk-Balloons/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/talk-balloons"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="MATCH_VERSION"

[[dependencies.${mod_id}]]
modId="forge"
mandatory = true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory = true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "modernnetworking"
mandatory = true
versionRange = "[${modernnetworking_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
mandatory = true
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-common.mixins.json"